MR109772/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from data import views
from rest_framework import routers
from django.conf.urls.static import static
from django.conf import settings

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)
router.register(r'books', views.BookViewSet)

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.note, name='note'),
    url(r'^shoes', views.shoe, name='shoe'),
    url(r'^shoe/(?P<id>[0-9]+)$', views.pickedShoe, name='pickedShoe'),
    url(r'^cart', views.get_cart, name='cart'),
    url(r'^products/buy/(?P<product_id>[0-9]+)/(?P<quantity>[0-9]+)$', views.add_to_cart, name = 'add_to_cart'),
    url(r'^products/remove/(?P<product_name>[^/]+)/(?P<selectedSize>[^/]+)$',
        views.remove_from_cart, name = 'remove_from_cart'),
    url(r'^pay', views.pay, name='pay'),
    url(r'^contact', views.contact, name='contact'),
    url(r'^thanks', views.thanks, name='thanks'),
    url(r'^pleaseLogIn', views.pleaseLogIn, name='pleaseLogIn'),
    url(r'^api/', include(router.urls)),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^api_auth/', include('rest_framework.urls', namespace='rest_framework'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

data/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
import os

# Create your models here.
class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    description = models.TextField
    publish_date = models.DateField(default=timezone.now)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    stock = models.IntegerField(default=0)
    year = models.IntegerField(max_length=4, default=0)

#def get_image_path(instance, filename):
#    return os.path.join('photos', str(instance.id), filename)

class Shoe(models.Model):
    brand_model = models.CharField(max_length=200)
    picture = models.ImageField(upload_to='photos', blank=True, null=True)
    description = models.TextField(default=0)
    price = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    blocked = models.BooleanField(default=False)
    def __str__(self):
        return(self.brand_model)

class Note(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(User, null=True, blank=True, editable=False)
    body = models.TextField(default=0)
    publish_date = models.DateTimeField(default=timezone.now)

class Size(models.Model):
    shoeID = models.ForeignKey(Shoe, default='1')
    size = models.CharField(max_length=10, default='0')

store/models.py
from django.db import models

# Create your models here.

data/forms.py
from django import forms

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)

data/views.py
from django.shortcuts import render, render_to_response
from data.models import Book, Shoe, Note, Size
from cart.cart import Cart

from django.contrib.auth.models import User, Group
from rest_framework import viewsets
from serializers import UserSerializer, GroupSerializer, BookSerializer

from django.core.mail import send_mail
from .forms import ContactForm
from django.shortcuts import redirect
from django.http import HttpResponseRedirect


def add_to_cart(request, product_id, quantity):
    if request.user.is_authenticated():
        product = Shoe.objects.get(id=product_id)
        cart = Cart(request)
        selectedSize = request.POST['selectedSize']
        cart.add(product, product.price, quantity, selectedSize)
        return render(request, 'cart.html', dict(cart=Cart(request)))
    else:
        return render(request, 'pleaseLogIn.html')


def remove_from_cart(request, product_name, selectedSize):
    product = Shoe.objects.get(brand_model=product_name)
    cart = Cart(request)
    cart.remove(product, selectedSize)
    return render(request, 'cart.html', dict(cart=Cart(request)))


def get_cart(request):
    return render(request, 'cart.html', dict(cart=Cart(request)))


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            sender = form.cleaned_data['sender']
            cc_myself = form.cleaned_data['cc_myself']

            recipients = ['test@test.com']
            if cc_myself:
                recipients.append(sender)

            send_mail(subject, message, sender, recipients)
            return HttpResponseRedirect('/thanks/')
            #return redirect('contact')

    else:
        form = ContactForm()

    return render(request, 'contact.html', {'form': form})


def thanks(request):
    return render(request, 'thanks.html')


def pleaseLogIn(request):
    return render(request, 'pleaseLogIn.html')


def pay(request):
    return render(request, 'pay.html')


def page(request):
    return render(request, 'page.html')


def data(request):
    context = {
        'BookCount' : Book.objects.count,
        'books' : Book.objects.all()}
    return render(request, 'data.html', context)


def shoe(request):
    context = {
        'ShoeCount' : Shoe.objects.count,
        'shoes' : Shoe.objects.all().filter(blocked = False)}
    return render(request, 'shoe.html', context)


def pickedShoe(request, id):
    context = {
        'shoe' : Shoe.objects.get(pk = id),
        'sizes' : Size.objects.all().filter(shoeID = id)}
    return render(request, 'pickedShoe.html', context)


def note(request):
    context = {
        'NoteCount' : Note.objects.count,
        'notes' : Note.objects.all().order_by('-publish_date')}
    return render(request, 'note.html', context)


class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer


class GroupViewSet(viewsets.ModelViewSet):
    queryset = Group.objects.all()
    serializer_class = GroupSerializer


class BookViewSet(viewsets.ModelViewSet):
    queryset = Book.objects.all()
    serializer_class = BookSerializer

store/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def home(request):
    return render(request, 'home.html')

def store(request):
    return render(request, 'store.html')

data/templates/base.html
{% extends 'bootstrap3/bootstrap3.html'%}

{% load staticfiles %}

{% load bootstrap3 %}

{% load bootstrap_themes %}

{% bootstrap_styles theme='simplex' type='min.css' %}

{% block bootstrap3_extra_head %}
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700&amp;subset=latin-ext" rel="stylesheet">
    <link href="{% static 'base/css/style.css'%}" rel="stylesheet">
{% endblock %}

{% block bootstrap3_title %}
    {% block title %}
        Sklep z butami
    {% endblock %}
{% endblock %}

{% block bootstrap3_content %}
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'note' %}">Sklep z butami</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'shoe' %}">Buty <span class="sr-only">(current)</span></a></li>
        <li><a href="{% url 'contact' %}">Kontakt</a></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li><span style="padding:15px; display:block; color: black">
            {% if user.is_authenticated %}
            Witaj, {% if user.first_name %}
                {{ user.first_name }}
            {% else %}
                {{ user.username }}
            {% endif %}!</span></li>
          <li><a href="{% url 'cart' %}"><span class="glyphicon glyphicon-shopping-cart"></span> Koszyk</a></li>
          <li><a href="{% url 'auth_logout' %}"><span class="glyphicon glyphicon-log-out"></span> Wyloguj się</a></li>
          {% else %}
          <li><span style="padding:15px; display:block; color: white">Witaj nieznajomy!</span></li>
          <li><a href="{% url 'auth_login' %}"><span class="glyphicon glyphicon-log-in"></span> Zaloguj się</a></li>
          <li><a href="{% url 'registration_register' %}"><span class="glyphicon glyphicon-user"></span> Zarejestruj się</a></li>
            {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container-fluid site-body">
    {% block body %}
    {% endblock %}
</div>

{% endblock %}

data/templates/books.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
You have {{ BookCount }} book{{ BookCount|pluralize }} in Your store

<table>
    <tr>
        <td><b>Title</b></td>
        <td><b>Author</b></td>
        <td><b>Price</b></td>
        <td><b>Stock</b></td>
        <td><b>Year</b></td>
    </tr>
    {% for book in books %}
    <tr>
        <td>{{book.title}}</td>
        <td>{{book.author}}</td>
        <td>{{book.price}}</td>
        <td>{{book.stock}}</td>
        <td>{{book.year}}</td>
    </tr>
    {% endfor %}
</table>
</body>
</html>

data/templates/cart.html
{% extends 'base.html' %}
{% load i18n %}

{% block body %}
<div class="container">
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Produkt</th>
                <th>Rozmiar</th>
                <th>Ilość</th>
                <th>Cena</th>
                <th> </th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart %}
            <tr>
                <td class="col-md-2">{{ item.product.brand_model }}</td>
                <td class="col-md-2">{{ item.size }}</td>
                <td class="col-md-2">{{ item.quantity }}</td>
                <td class="col-md-2">{{ item.total_price }}</td>
                <td class="col-md-1"><a class="btn btn-primary" href="{% url 'remove_from_cart' item.product.brand_model item.size %}">Usuń z koszyka</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <h2>Total: {{ cart.summary }}</h2>
    <a class="btn btn-primary" href="{% url 'shoe'  %}">Kontunuuj zakupy</a>
    <a class="btn btn-primary" href="{% url 'pay'  %}">Płacę</a>
</div>
{% endblock %}

data/templates/contact.html
{% extends "base.html" %}
{% load i18n %}

{% block body %}

<div class="col-md-6 col-md-offset-3">
<div class="panel panel-info">
    <div class="panel-heading">Kontakt</div>
    <div class="panel-body">

<form role="form" action="" method="post">
  {% csrf_token %}
  <div class="form-group">
      <p><label for="id_subject">Temat:</label>
        <input id="id_subject" type="text" class="form-control" name="subject" maxlength="100" required /></p>
  </div>
  <div class="form-group">
      <p><label for="id_message">Treść:</label>
        <textarea name="message" id="id_message" class="form-control" rows="5" required></textarea></p>
  </div>
  <div class="form-group">
      <p><label for="id_sender">Email:</label>
        <input type="email" name="sender" class="form-control" id="id_sender" required /></p>
  </div>
  <div class="form-group">
      <p><label for="id_cc_myself">Kopia do siebie:</label>
        <input type="checkbox" name="cc_myself" id="id_cc_myself" /></p>
  </div>

  <button type="submit" class="btn btn-default">Wyślij</button>
</form>


</div>
</div>
</div>

{% endblock %}

data/templates/data.html
{% extends 'base.html'%}

{% block body %}

<div class="row">
  {% for book in books %}
  <div class="col-sm-6 col-md-4">

    <div class="thumbnail">
      <!--<img src="..." alt="...">-->
      <div class="caption">
        <h3>{{book.title}}</h3>
        <p>Autor: {{book.author}}</p>
        <p>Cena: {{book.price}}</p>
        <p>Liczba: {{book.stock}}</p>
        <p>Rok wydania: {{book.year}}</p>
        <p><a href="#" class="btn btn-primary" role="button">Kup</a></p>
      </div>
    </div>
   </div>
  {% endfor %}
</div>

{% endblock %}

data/templates/myname.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
Mam na imię {{ imie }} {{ nazwisko }}. Mój numer indeksu to {{indeks}}.
</body>
</html>

data/templates/note.html
{% extends 'base.html'%}

{% block body %}

<style>
.notebody{
word-wrap: break-word;
}
</style>

<div class="row">
  {% for note in notes %}
  <div class="col-md-8 col-md-offset-2">

    <div class="thumbnail">
      <!--<img src="..." alt="...">-->
      <div class="caption">
        <h3>{{note.title}}</h3>
        <p>Autor: {{note.author}}</p>
        <p class="notebody">{{note.body}}</p>
        <p>Opublikowano: {{note.publish_date}}</p>
      </div>
    </div>
   </div>
  {% endfor %}
</div>

{% endblock %}

data/templates/page.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
My page
</body>
</html>

data/templates/pay.html
{% extends "base.html" %}
{% load i18n %}

{% block body %}

<div class="col-md-6 col-md-offset-3">
<div class="panel panel-info">
    <div class="panel-heading">Wybierz metodę płatności</div>
    <div class="panel-body">

    <p>Wybierz metodę płatności:</p>

</form>


</div>
</div>
</div>

{% endblock %}

data/templates/pickedShoe.html
{% extends 'base.html'%}

{% block body %}

<style>
.shoe-picture{
width: 100%;
}

.btn{
margin-top: 10px;
}

</style>
<div class="row">
  <div class="col-sm-6 col-md-4">

    <div class="thumbnail">
      {% load static %}
      <img class="shoe-picture" src={{shoe.picture.url}} />

    </div>
   </div>
   <div class="col-sm-6 col-md-4">
     <div class="caption">
        <h1>{{shoe.brand_model}}</h1>

        <p><b>Cena:</b> {{shoe.price}}</p>
        <form method = "post" action = "{% url 'add_to_cart' shoe.id 1 %}">
        {% csrf_token %}
        <label for="sel1">Rozmiar:</label>
          <select class="form-control" id="sel1" name="selectedSize">
            {% for size in sizes %}
                <option>{{size.size}}</option>
            {% endfor %}
          </select>
        <input class="btn btn-primary" type = "submit" value="Dodaj do koszyka">
        </form>
      </div>
   </div>
</div>

<p><b>Opis:</b>  {{shoe.description}}</p>

{% endblock %}

data/templates/pleaseLogIn.html
{% extends "base.html" %}
{% load i18n %}

{% block body %}

<div class="col-md-6 col-md-offset-3">
<div class="panel panel-info">
    <div class="panel-heading">Zaloguj się</div>
    <div class="panel-body">

    <p>Zaloguj się, aby dodać produkty do koszyka!</p>

</form>


</div>
</div>
</div>

{% endblock %}

data/templates/shoe.html
{% extends 'base.html'%}

{% block body %}

<style>
.shoe-picture{
    width:100%;}

.imageclass{
    min-height: 200px;
    }
</style>

<div class="row">
  {% for shoe in shoes %}
  <div class="col-sm-3 col-md-3">

    <div class="thumbnail">
      {% load static %}
      <div class="imageclass">
      <a href="{% url 'pickedShoe' shoe.id %}">
        <img class="shoe-picture" src={{shoe.picture.url}} />
      </a>
      </div>
      <div class="caption">
        <h3>{{shoe.brand_model}}</h3>
        <p>Cena: {{shoe.price}}</p>
      </div>
    </div>
   </div>
  {% endfor %}
</div>

{% endblock %}

data/templates/thanks.html
{% extends "base.html" %}
{% load i18n %}

{% block body %}

<div class="col-md-6 col-md-offset-3">
<div class="panel panel-info">
    <div class="panel-heading">Dziękujemy</div>
    <div class="panel-body">

    <p>Dziękujemy za wysłanie maila!</p>

</form>


</div>
</div>
</div>

{% endblock %}

store/templates/home.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
Hello {% if request.user.is_authenticated %}
        {% if request.user.first_name != '' %}
            {{request.user.first_name}}
        {% else %}
            {{request.user.username}}
        {% endif %}
      {% endif %}!
</body>
</html>

store/templates/index.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
Index
</body>
</html>

store/templates/store.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
Welcome to the store!
</body>
</html>